name: Dem Read file Readme

on:
  push:
    branches: ["main"]

jobs:
  Thuc_hanh_doc_file:
    runs-on: ubuntu-latest

    steps:
      - name: Buoc 1 - xin chao
        run: echo "hello world"
        
      - name: Buoc 2 - tai code
        uses: actions/checkout@v4
        
      - name: Buoc 3 - doc file
        run: cat README.md
